
package view;

import controller.RoomController;
import javax.swing.JOptionPane;
import model.RoomInfo;


public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form UserFrm
     */
    public FrameUser() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoubleRoomPictureLabel = new javax.swing.JLabel();
        FamilyRoomPictureLabel = new javax.swing.JLabel();
        DoubleRoomLabel = new javax.swing.JLabel();
        ThreeRoomLabel = new javax.swing.JLabel();
        OneRoomLabel = new javax.swing.JLabel();
        SingleRoomPictureLabel = new javax.swing.JLabel();
        OneRoomRentButton = new javax.swing.JButton();
        TwoRoomRentButton = new javax.swing.JButton();
        ThreeRoomRentButton = new javax.swing.JButton();
        OneRoomRestButton = new javax.swing.JButton();
        ThreeRoomRestButton2 = new javax.swing.JButton();
        TwoRoomRestButton = new javax.swing.JButton();
        OneLabel = new javax.swing.JLabel();
        TwoLabel = new javax.swing.JLabel();
        ThreeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OrderMenu = new javax.swing.JMenu();
        SearchOrderMenuItem = new javax.swing.JMenuItem();
        CheckOutMenu = new javax.swing.JMenu();
        CheckOutMenuItem = new javax.swing.JMenuItem();
        UserMenu = new javax.swing.JMenu();
        HelpMenuItem = new javax.swing.JMenuItem();
        ServerMenu = new javax.swing.JMenu();
        ServerMenuItem = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        WelcomMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserMain");
        setLocation(new java.awt.Point(400, 100));

        DoubleRoomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ë«ÈË·¿.png"))); // NOI18N
        DoubleRoomPictureLabel.setText("jLabel1");

        FamilyRoomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/¼ÒÍ¥·¿.png"))); // NOI18N
        FamilyRoomPictureLabel.setText("jLabel2");

        DoubleRoomLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        DoubleRoomLabel.setText("Double Room");

        ThreeRoomLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        ThreeRoomLabel.setText("Family room");

        OneRoomLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        OneRoomLabel.setText("SingleRoom");

        SingleRoomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/µ¥ÈË·¿.png"))); // NOI18N
        SingleRoomPictureLabel.setText("jLabel8");

        OneRoomRentButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        OneRoomRentButton.setText("Reservation");
        OneRoomRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneRoomRentButtonActionPerformed(evt);
            }
        });

        TwoRoomRentButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        TwoRoomRentButton.setText("Reservation");
        TwoRoomRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoRoomRentButtonActionPerformed(evt);
            }
        });

        ThreeRoomRentButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        ThreeRoomRentButton.setText("Reservation");
        ThreeRoomRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeRoomRentButtonActionPerformed(evt);
            }
        });

        OneRoomRestButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        OneRoomRestButton.setText("Query Remaining Rooms");
        OneRoomRestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneRoomRestButtonActionPerformed(evt);
            }
        });

        ThreeRoomRestButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        ThreeRoomRestButton2.setText("Query Remaining Rooms");
        ThreeRoomRestButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeRoomRestButton2ActionPerformed(evt);
            }
        });

        TwoRoomRestButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        TwoRoomRestButton.setText("Query Remaining Rooms");
        TwoRoomRestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoRoomRestButtonActionPerformed(evt);
            }
        });

        OneLabel.setText("0");

        TwoLabel.setText("0");

        ThreeLabel.setText("0");

        OrderMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/003-calendar.png"))); // NOI18N
        OrderMenu.setText("Reserve");

        SearchOrderMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/°ïÖú.png"))); // NOI18N
        SearchOrderMenuItem.setText("Query Booking Results");
        SearchOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchOrderMenuItemActionPerformed(evt);
            }
        });
        OrderMenu.add(SearchOrderMenuItem);

        jMenuBar1.add(OrderMenu);

        CheckOutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/´´×÷.png"))); // NOI18N
        CheckOutMenu.setText("Check-out");

        CheckOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/´´×÷.png"))); // NOI18N
        CheckOutMenuItem.setText("Check-out Form");
        CheckOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutMenuItemActionPerformed(evt);
            }
        });
        CheckOutMenu.add(CheckOutMenuItem);

        jMenuBar1.add(CheckOutMenu);

        UserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/022-users-1.png"))); // NOI18N
        UserMenu.setText("User Help");

        HelpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/°ïÖú.png"))); // NOI18N
        HelpMenuItem.setText("The Manual");
        HelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(HelpMenuItem);

        jMenuBar1.add(UserMenu);

        ServerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/023-users.png"))); // NOI18N
        ServerMenu.setText("Room Service");

        ServerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/015-smile.png"))); // NOI18N
        ServerMenuItem.setText("Room Service Request");
        ServerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerMenuItemActionPerformed(evt);
            }
        });
        ServerMenu.add(ServerMenuItem);

        jMenuBar1.add(ServerMenu);

        ExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ê§°Ü.png"))); // NOI18N
        ExitMenu.setText("Log Out");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });

        ExitMenuItem.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        ExitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ê§°Ü.png"))); // NOI18N
        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        ExitMenu.add(ExitMenuItem);

        jMenuBar1.add(ExitMenu);

        WelcomMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/»áÔ±.png"))); // NOI18N
        WelcomMenu.setText("Welcome To Our Hotel");
        jMenuBar1.add(WelcomMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(659, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OneRoomLabel)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OneRoomRentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OneRoomRestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TwoRoomRestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TwoRoomRentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThreeRoomRestButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThreeRoomRentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DoubleRoomLabel)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ThreeRoomLabel)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DoubleRoomPictureLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(SingleRoomPictureLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FamilyRoomPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGap(57, 228, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(OneRoomLabel)
                .addGap(18, 18, 18)
                .addComponent(OneRoomRestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OneRoomRentButton)
                .addGap(106, 106, 106)
                .addComponent(DoubleRoomLabel)
                .addGap(18, 18, 18)
                .addComponent(TwoRoomRestButton)
                .addGap(4, 4, 4)
                .addComponent(TwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TwoRoomRentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(ThreeRoomLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThreeRoomRestButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThreeRoomRentButton)
                .addGap(72, 72, 72))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SingleRoomPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(DoubleRoomPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(FamilyRoomPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThreeRoomRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeRoomRentButtonActionPerformed
        ReserveInfoAdd addrentfrm = new ReserveInfoAdd();
        addrentfrm.setVisible(true);   // Open ReserveInfoAdd and display the form;
    }//GEN-LAST:event_ThreeRoomRentButtonActionPerformed

    private void TwoRoomRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoRoomRentButtonActionPerformed
        ReserveInfoAdd addrentfrm = new ReserveInfoAdd();
        addrentfrm.setVisible(true);   // Open ReserveInfoAdd and display the form:
    }//GEN-LAST:event_TwoRoomRentButtonActionPerformed

    private void OneRoomRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneRoomRentButtonActionPerformed
        ReserveInfoAdd addrentfrm = new ReserveInfoAdd();
        addrentfrm.setVisible(true);  // Open ReserveInfoAdd and display the form:
    }//GEN-LAST:event_OneRoomRentButtonActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        String message2 = "Are you sure you want to quit the system?";
        if (JOptionPane.showConfirmDialog(this, message2) == JOptionPane.OK_OPTION) {
            System.exit(0);        // Prompt whether to exit the system, and if so, exit the system:
    }//GEN-LAST:event_ExitMenuItemActionPerformed
    }
    private void OneRoomRestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneRoomRestButtonActionPerformed
        //Check the number of single rooms available ;
        RoomInfo roomInfo = new RoomInfo();
        roomInfo.setRoomType("Single Room");
        RoomController roomDB = new RoomController();
        String i =String.valueOf(roomDB.getRoomNumber(roomInfo));
        OneLabel.setText(i);

    }//GEN-LAST:event_OneRoomRestButtonActionPerformed

    private void ThreeRoomRestButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeRoomRestButton2ActionPerformed
        //Check the number of double rooms available ;
        RoomInfo roomInfo = new RoomInfo();
        roomInfo.setRoomType("Family Room");
        RoomController roomDB = new RoomController();
        String i =String.valueOf(roomDB.getRoomNumber(roomInfo));
        ThreeLabel.setText(i);
    }//GEN-LAST:event_ThreeRoomRestButton2ActionPerformed

    private void TwoRoomRestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoRoomRestButtonActionPerformed
        //Check the number of family rooms available ;
        RoomInfo roomInfo = new RoomInfo();
        roomInfo.setRoomType("Double Room");
        RoomController roomDB = new RoomController();
        String i =String.valueOf(roomDB.getRoomNumber(roomInfo));
        TwoLabel.setText(i);
    }//GEN-LAST:event_TwoRoomRestButtonActionPerformed

    private void HelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuItemActionPerformed
        //Display manual;
        String message = "This is the manual!\n Hour Room$60/H \n Standard Room$100/D \n Single rooms are paid according to the time of use  \n  Double room costs 50% more than a single room \n Family Room pay 100% more than single rooms";
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_HelpMenuItemActionPerformed

    private void SearchOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchOrderMenuItemActionPerformed
        // Open ReserveInfoCheck and display the form:
        new ReserveInfoCheck().setVisible(true);
    }//GEN-LAST:event_SearchOrderMenuItemActionPerformed

    private void CheckOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutMenuItemActionPerformed
        // Open ReserveInfoAdd and display the form::
        new ReserveInfoAdd().setVisible(true);
    }//GEN-LAST:event_CheckOutMenuItemActionPerformed

    private void ServerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerMenuItemActionPerformed
        // Open ReserveInfoAdd and display the form:
        new RequestInfoAdd().setVisible(true);
    }//GEN-LAST:event_ServerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CheckOutMenu;
    private javax.swing.JMenuItem CheckOutMenuItem;
    private javax.swing.JLabel DoubleRoomLabel;
    private javax.swing.JLabel DoubleRoomPictureLabel;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JLabel FamilyRoomPictureLabel;
    private javax.swing.JMenuItem HelpMenuItem;
    private javax.swing.JLabel OneLabel;
    private javax.swing.JLabel OneRoomLabel;
    private javax.swing.JButton OneRoomRentButton;
    private javax.swing.JButton OneRoomRestButton;
    private javax.swing.JMenu OrderMenu;
    private javax.swing.JMenuItem SearchOrderMenuItem;
    private javax.swing.JMenu ServerMenu;
    private javax.swing.JMenuItem ServerMenuItem;
    private javax.swing.JLabel SingleRoomPictureLabel;
    private javax.swing.JLabel ThreeLabel;
    private javax.swing.JLabel ThreeRoomLabel;
    private javax.swing.JButton ThreeRoomRentButton;
    private javax.swing.JButton ThreeRoomRestButton2;
    private javax.swing.JLabel TwoLabel;
    private javax.swing.JButton TwoRoomRentButton;
    private javax.swing.JButton TwoRoomRestButton;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JMenu WelcomMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
