/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RentController;
import javax.swing.JOptionPane;
import model.RentInfo;
import util.StringUtil;

/**
 *
 * @author hasee
 */
public class RentInfoAdd extends javax.swing.JFrame {

    /**
     * Creates new form AddRentFrm
     */
    public RentInfoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RentalRoomLabel = new javax.swing.JLabel();
        RoomTypeLabel = new javax.swing.JLabel();
        HousingDayLabel = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        DepositLabel = new javax.swing.JLabel();
        RentTypeComboBox = new javax.swing.JComboBox<>();
        RoomTypeComboBox = new javax.swing.JComboBox<>();
        RemarkLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        IDNumberLabel = new javax.swing.JLabel();
        RentDaysTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        MoneyTextField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        RemarkTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new housing information");
        setLocation(new java.awt.Point(480, 280));

        RentalRoomLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        RentalRoomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ô¤¶©·¿¼ä±£Ö¤.png"))); // NOI18N
        RentalRoomLabel.setText("Type Of Rental:");

        RoomTypeLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        RoomTypeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/·¿¼ä.png"))); // NOI18N
        RoomTypeLabel.setText("RoomType :");

        HousingDayLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        HousingDayLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/003-calendar.png"))); // NOI18N
        HousingDayLabel.setText("Housing days:");

        ResetButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ê§°Ü.png"))); // NOI18N
        ResetButton.setText("Reset Information");
        ResetButton.setToolTipText("");
        ResetButton.setActionCommand("");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        DepositLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        DepositLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ç®°ü1.png"))); // NOI18N
        DepositLabel.setText("Deposit :");
        DepositLabel.setToolTipText("");

        RentTypeComboBox.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        RentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour Room", "Standard Room" }));
        RentTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentTypeComboBoxActionPerformed(evt);
            }
        });

        RoomTypeComboBox.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        RoomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Double Room", "Family Room" }));
        RoomTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeComboBoxActionPerformed(evt);
            }
        });

        RemarkLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        RemarkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/´´×÷.png"))); // NOI18N
        RemarkLabel.setText("Remark :");

        SubmitButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        SubmitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ôö¼Ó.png"))); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        NameTextField.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N

        IDNumberLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        IDNumberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Éí·ÝÖ¤ÕýÃæ.png"))); // NOI18N
        IDNumberLabel.setText("ID Number:");

        RentDaysTextField.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N

        IDTextField.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        MoneyTextField.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N

        NameLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N
        NameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ÐÕÃû£¬Ö¤¼þ.png"))); // NOI18N
        NameLabel.setText("Name :");

        RemarkTextField.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IDNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RentalRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoomTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DepositLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HousingDayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RemarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MoneyTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RemarkTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RentDaysTextField)
                            .addComponent(RentTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RentalRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HousingDayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RentDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        IDTextField.setText("");
        NameTextField.setText("");
        RentDaysTextField.setText("");
        MoneyTextField.setText("");
        RemarkTextField.setText("");
        RentTypeComboBox.setSelectedIndex(0);
        RoomTypeComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_ResetButtonActionPerformed

    private void RoomTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTypeComboBoxActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        //The submit button disappears after adding data to the database;
        String ID=IDTextField.getText().toString();
        String Name=NameTextField.getText().toString();
        String Rentdays=RentDaysTextField.getText().toString();
        String Money=MoneyTextField.getText().toString();
        String Remark=RemarkTextField.getText();
        String selectedRentItem = (String)RentTypeComboBox.getSelectedItem();
        String selectedRoomItem = (String)RoomTypeComboBox.getSelectedItem();
        //Information is required. If it is empty, it indicates that information needs to be added;
        if(StringUtil.isEmpty(ID)){
            JOptionPane.showMessageDialog(this, "ID cannot be empty!");
			return;
        }
        if(StringUtil.isEmpty(Name)){
            JOptionPane.showMessageDialog(this, "ID name cannot be empty!");
			return;
        }
        if(StringUtil.isEmpty(Rentdays)){
            JOptionPane.showMessageDialog(this, "Booking days cannot be empty!");
			return;
        }
        if(StringUtil.isEmpty(Money)){
            JOptionPane.showMessageDialog(this, "The deposit cannot be empty!");
			return;
        }
        //Add data column;
        RentInfo rentInfo =new RentInfo();
        rentInfo.setGuestIDnumber(ID);
        rentInfo.setGuestName(Name);
        rentInfo.setRentDays(Integer.parseInt( Rentdays ));
        rentInfo.setRentType(selectedRentItem);
        rentInfo.setRoomType(selectedRoomItem);
        rentInfo.setAntecedentMoney(Integer.parseInt( Money ));
        rentInfo.setRemark(Remark);
        
        RentController rentDB=new RentController();   
        if(rentDB.addRent(rentInfo)){
            JOptionPane.showMessageDialog(this, "Rental information added successfully!");
            System.out.println("Rental information added successfully!");
	}else{
            JOptionPane.showMessageDialog(this, "Rental information added failed!");
	}
        rentDB.closeBaseDB();
        this.setVisible(true);
        
        IDTextField.setText("");
        NameTextField.setText("");
        RentDaysTextField.setText("");
        MoneyTextField.setText("");
        RemarkTextField.setText("");
        RentTypeComboBox.setSelectedIndex(0);
        RoomTypeComboBox.setSelectedIndex(0);
        
        
//        this.dispose();
//        MainFrm main=new MainFrm();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void RentTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentInfoAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepositLabel;
    private javax.swing.JLabel HousingDayLabel;
    private javax.swing.JLabel IDNumberLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField MoneyTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel RemarkLabel;
    private javax.swing.JTextField RemarkTextField;
    private javax.swing.JTextField RentDaysTextField;
    private javax.swing.JComboBox<String> RentTypeComboBox;
    private javax.swing.JLabel RentalRoomLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JComboBox<String> RoomTypeComboBox;
    private javax.swing.JLabel RoomTypeLabel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
