
package view;

import controller.RequestController;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RequestInfo;


public class RequestInfoList extends javax.swing.JFrame {

    /**
     * Creates new form RequestInfoList
     */
    public RequestInfoList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDNameLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        DataNoteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestInfoListTable = new javax.swing.JTable();
        IDLabel = new javax.swing.JLabel();
        DeleteTextField = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        DeleteNoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Request processing interface");
        setLocation(new java.awt.Point(480, 280));
        setName("∑˛ŒÒ…Í«Î±Ì"); // NOI18N

        IDNameLabel.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        IDNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/…Ì∑›÷§’˝√Ê.png"))); // NOI18N
        IDNameLabel.setText("Please Enter Your Name :");

        SearchTextField.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(153, 153, 153));
        SearchTextField.setToolTipText("123");
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/≤È—Ø.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        DataNoteLabel.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        DataNoteLabel.setForeground(new java.awt.Color(102, 102, 102));
        DataNoteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ã· æ.png"))); // NOI18N
        DataNoteLabel.setText("If no input, all data will be returned by default)");

        RequestInfoListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request", "Name", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RequestInfoListTable.setRowHeight(30);
        jScrollPane1.setViewportView(RequestInfoListTable);

        IDLabel.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        IDLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/…Ì∑›÷§’˝√Ê.png"))); // NOI18N
        IDLabel.setText("Selected ID :");

        DeleteTextField.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        DeleteTextField.setForeground(new java.awt.Color(153, 153, 153));
        DeleteTextField.setToolTipText("123");
        DeleteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTextFieldActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ºı…Ÿ.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DeleteNoteLabel.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        DeleteNoteLabel.setForeground(new java.awt.Color(102, 102, 102));
        DeleteNoteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ã· æ.png"))); // NOI18N
        DeleteNoteLabel.setText("(Delete the selected data in the table)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IDNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DataNoteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(DeleteNoteLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(DataNoteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteButton)
                        .addComponent(DeleteNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        //SearchButton :The data for each column is read from the database and exported to the List;
        DefaultTableModel table = (DefaultTableModel) RequestInfoListTable.getModel();
        table.setRowCount(0);
        RequestController requestDB = new RequestController();
        RequestInfo requestInfo = new RequestInfo();
        requestInfo.setName(SearchTextField.getText().toString());
        List<RequestInfo> requestList = requestDB.getRequestList(requestInfo);
        for (RequestInfo requestInfoItem : requestList) {
            Vector v = new Vector();
            v.add(requestInfoItem.getRequest());
            v.add(requestInfoItem.getName());
            v.add(requestInfoItem.getId());
            table.addRow(v);
        }
        requestDB.closeBaseDB();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void DeleteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteTextFieldActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        
        //Delete the selected database information and import it into the rent table;
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete it?") != JOptionPane.OK_OPTION) {
            return;
        }
        int index = RequestInfoListTable.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please select the data to be deleted from the table!");
            return;
        }
        DefaultTableModel dft = (DefaultTableModel) RequestInfoListTable.getModel();
        String SelectedId = dft.getValueAt(RequestInfoListTable.getSelectedRow(), 0).toString();
        RequestController requestDB = new RequestController();
        if (requestDB.delete(SelectedId)) {
            JOptionPane.showMessageDialog(this, "Delete successful!");
        } else {
            JOptionPane.showMessageDialog(this, "Deletion failed!");
        }
        requestDB.closeBaseDB();
        //  setTable(new RentInfo());
        dft.setRowCount(0);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestInfoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestInfoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestInfoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestInfoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestInfoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataNoteLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DeleteNoteLabel;
    private javax.swing.JTextField DeleteTextField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IDNameLabel;
    private javax.swing.JTable RequestInfoListTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
